export const API_LOGIN = '/login'
export const API_LOGOUT = '/logout'
export const API_PW_CHANGE = '/password'
export const API_GET_TOKENS = '/tokens'
export const API_GET_ACCESSTOKEN = '/accesstoken'
export const API_POST_RESOURCE_IMAGE = '/resource-file/'
export const API_RESOURCE = '/resource/'
